import Head from "next/head";
import type { NextPage } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import SearchBar from "../components/SearchBar";
import Gallery from "../components/Gallery";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const getImage = (images): string => {
  if (!images || !images[0]) return "";
  if (images[0].type === "video/mp4") return images[0].gifv.slice(0, -1);
  return images[0].link;
};

const Home: NextPage = () => {
  const router = useRouter();
  const imageId = router.query.image;
  const [imageObject, setImageObject] = useState({
    title: "",
    description: "",
    link: "",
    id: "",
    views: "",
  });
  useEffect(() => {
    fetch(`http://localhost:5000/image/${imageId}`, { mode: "cors" })
      .then((res) => res.json())
      .then((res) => setImageObject(res))
      .catch((err) => console.log({ err }));
  }, [imageId]);
  const {
    title = "",
    description = "",
    id = "",
    views = "",
    images,
    ups,
    downs,
    score,
  } = imageObject;

  const imageLink = getImage(images);
  return (
    <div>
      <Head>
        <title>Imgur: {title || "Image"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">Imgur: {id}</h1>

      <div className="">
        <img
          src={imageLink}
          alt="Cinque Terre"
          width="800"
          //   height="400"
        />
        <h3 className="text-center">title: {title}</h3>
        <div className="desc">description: {description}</div>
        <p>Upvotes: {ups}</p>
        <p>downvotes: {downs}</p>
        <p>score: {score}</p>
      </div>
    </div>
  );
};

export default Home;
