import Head from "next/head";
import type { NextPage } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import SearchBar from "../components/SearchBar";
import Gallery from "../components/Gallery";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [imageData, setImageData] = useState([]);

  const [section, changeSection] = useState("hot");
  const [sort, changeSort] = useState("viral");
  const [window, changeWindow] = useState("day");
  useEffect(() => {
    fetch(`http://localhost:5000/?section=${section}&window=${window}&sort=${sort}`, { mode: "cors" })
      .then((res) => res.json())
      .then((res) => setImageData(res))
      .catch((err) => console.log({ err }));
  }, [sort, window, section]);
  return (
    <div>
      <Head>
        <title>Imgur Nextjs Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">Imgur Gallery</h1>
      <SearchBar
        section={section}
        changeSection={changeSection}
        sort={sort}
        changeSort={changeSort}
        window={window}
        changeWindow={changeWindow}
      />
      <Gallery data={imageData} />
    </div>
  );
};

export default Home;
