import Head from "next/head";
import type { NextPage } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import SearchBar from "../components/SearchBar";
import Gallery from "../components/Gallery";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [imageData, setImageData] = useState([]);
  useEffect(() => {
    fetch("http://localhost:5000/", { mode: "cors" })
      .then((res) => res.json())
      .then((res) => setImageData(res))
      .catch((err) => console.log({ err }));
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">Imgur Gallery</h1>
      <SearchBar />
      <Gallery data={imageData} />
    </div>
  );
};

export default Home;
